export const ROOT_ROUTES = {
  API: "/api",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  LOGOUT: "/logout",
  CLEANUP: "/cleanup",
  ROOT: "/",
  WEEK: "/week",
  DAY: "/day",
  DAY_DATE: "/day/:dateString",
  NOW: "/now",
};
